<?
// BUILD ADS
$allAds=array(
    1=>array(   1=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad_yourbody.gif"=>"health_bodyguy.php",
                            "new/ad_pharm.gif"=>"health_pharmo.php"),
                2=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad_yourbody.gif"=>"health_bodyguy.php",
                            "new/ad_pharm.gif"=>"health_pharmo.php"),
                3=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad_yourbody.gif"=>"health_bodyguy.php",
                            "new/ad_pharm.gif"=>"health_pharmo.php"),
                4=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad_yourbody.gif"=>"health_bodyguy.php",
                            "new/ad_pharm.gif"=>"health_pharmo.php")),
    2=>array(   1=>array(   "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "ad_cigchemicals.gif"=>"news_cig-quiz.php",
                            "ad_costben.gif"=>"news_cost-benefits.php"),
                2=>array(   "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad_pharm.gif"=>"health_pharmo.php",
                            "ad_benefits.gif"=>"health_manual-2g.php"),
                3=>array(   "ad_forum_quitworries.gif"=>"/forum/viewforum.php?f=1",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "ad_dealwtriggers.gif"=>"health_manual-3g.php"),
                4=>array(   "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad_pharm.gif"=>"health_pharmo.php",
                            "new/ad_cravingshelp.gif"=>"health_manual-4b.php")),
    3=>array(   1=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-8.jpg"=>"health_tips-talkWithDoc.php",
                            "ad_cigchemicals.gif"=>"news_cig-quiz.php"),
                2=>array(   "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-1.jpg"=>"community_success.php",
                            "ad_cigchemicals.gif"=>"news_cig-quiz.php"),
                3=>array(   "ad_forum_quitworries.gif"=>"/forum/viewforum.php?f=1",
                            "ad_dealwtriggers.gif"=>"health_manual-3g.php",
                            "new/ad-6.jpg"=>"health_tips-relaxation.php"),
                4=>array(   "ad_forum_quitdate3.gif"=>"/forum/viewforum.php?f=1",
                            "ad_reward.gif"=>"health_manual-4h.php",
                            "new/ad-1.jpg"=>"community_success.php")),
    4=>array(   1=>array(   "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-6.jpg"=>"health_tips-relaxation.php"),
                2=>array(   "new/ad-2.jpg"=>"you_journal.php",
                            "ad_pharmquiz.gif"=>"health_pharmo.php",
                            "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1"),
                3=>array(   "ad_dealwtriggers.gif"=>"health_manual-3g.php",
                            "ad_forum_quitdate.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-8.jpg"=>"health_tips-talkWithDoc.php"),
                4=>array(   "new/ad_cravingshelp.gif"=>"health_manual-4b.php",
                            "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-1.jpg"=>"community_success.php")),
    5=>array(   1=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                2=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                3=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                4=>array(   "new/ad_forum.gif"=>"/forum/viewforum.php?f=1",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php")),
    6=>array(   1=>array(   "ad_benefits.gif"=>"health_manual-2g.php",
                            "new/ad-5.gif"=>"health_tips-sleep.php",
                            "new/ad_forum.gif"=>"/forum/viewforum.php?f=1"),
                2=>array(   "new/ad-8.gif"=>"health_tips-talkWithDoc.php",
                            "ad_pharmquiz.gif"=>"health_pharmo.php",
                            "new/ad_forum.gif"=>"/forum/viewforum.php?f=1"),
                3=>array(   "ad_cravingworry.gif"=>"health_manual-4b.php",
                            "new/ad-5.gif"=>"health_tips-sleep.php",
                            "new/ad_forum_quitdate2.gif"=>"/forum/viewforum.php?f=1"),
                4=>array(   "new/ad-2.jpg"=>"you_journal.php",
                            "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-cravingshelp.gif"=>"health_manual-4b.php")),
    7=>array(   1=>array(   "ad_cigchemicals.gif"=>"news_cig-quiz.php",
                            "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-7.gif"=>"health_tips-memory.php"),
                2=>array(   "ad_forum_quitworries.gif"=>"/forum/viewforum.php?f=1",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad-4.gif"=>"news.php"),
                3=>array(   "new/ad-6.gif"=>"health_tips-relaxation.php",
                            "ad_setquitdate.gif"=>"health_manual-3l.php",
                            "ad_forum_quitdate.gif"=>"/forum/viewforum.php?f=1"),
                4=>array(   "ad_reward.gif"=>"health_manual-4h.php",
                            "new/ad-2.jpg"=>"you_journal.php",
                            "ad_forum_quitdate3.gif"=>"/forum/viewforum.php?f=1")),
    8=>array(   1=>array(   "ad_costben.gif"=>"news_cost-benefits.php",
                            "new-ad3.gif"=>"health_manual-1g2.php",
                            "new/ad-forum.gif"=>"/forum/viewforum.php?f=1"),
                2=>array(   "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "ad9.gif"=>"forum/viewforum.php?f=1",
                            "new-ad1.gif"=>"community_success.php"),
                3=>array(   "ad_benefits.gif"=>"health_manual-2g.php",
                            "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1",
                            "ad_pharmquiz.gif"=>"health_pharmo.php"),
                4=>array(   "new/ad-6.jpg"=>"health_tips-relaxation.php",
                            "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-cravingshelp.gif"=>"health_manual-4b.php")),
    9=>array(   1=>array(   "ad_cigchemicals.gif"=>"news_cig-quiz.php",
                            "new/ad_pharm.gif"=>"health_pharmo.php",
                            "ad_forum_keepsmoking.gif"=>"/forum/viewforum.php?f=1"),
                2=>array(   "ad_yourbody.gif"=>"health_bodyguy.php",
                            "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad_pharm.gif"=>"health_pharmo.php"),
                3=>array(   "new/ad_forum_quitdate2.gif"=>"/forum/viewforum.php?f=1",
                            "new/ad-7.gif"=>"health_tips-memory.php",
                            "new/ad-3.gif"=>"health_manual-1g2.php"),
                4=>array(   "ad_reward.gif"=>"health_manual-4h.php",
                            "new/ad-8.jpg"=>"health_tips-talkWithDoc.php",
                            "ad_forum_quitting.gif"=>"/forum/viewforum.php?f=1")),
    10=>array(  1=>array(   "new-ad1.gif"=>"community_success.php",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad-forum.gif"=>"/forum/viewforum.php?f=1"),
                2=>array(   "new-ad1.gif"=>"community_success.php",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad-forum.gif"=>"/forum/viewforum.php?f=1"),
                3=>array(   "new-ad1.gif"=>"community_success.php",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad-forum.gif"=>"/forum/viewforum.php?f=1"),
                4=>array(   "new-ad1.gif"=>"community_success.php",
                            "ad_costben.gif"=>"news_cost-benefits.php",
                            "new/ad-forum.gif"=>"/forum/viewforum.php?f=1")),
    11=>array(  1=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                2=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                3=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                4=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php")),
    12=>array(  1=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                2=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                3=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php"),
                4=>array(   "new/ad_forum.gif"=>"health_manual-1a.php",
                            "ad2.gif"=>"health_manual-1a.php",
                            "ad3.gif"=>"health_manual-1a.php",
                            "ad4.gif"=>"health_manual-1a.php")));
while (list($k,$v)=each($allAds[$weekNum][$userSpecs["stage"]])) {
    if (($v=="/forum/viewforum.php?f=1") && ($newPosts>0)) $k="ad_forumNEW2.gif";
?>
    <a href="<?=$v?>"><img src="images/ads/<?=$k?>" border=0 alt=""></a><br>
<?
}
?>


